SELECT  [ProductKey]
      ,[OrderDateKey]
      --,[DueDateKey]
      --,[ShipDateKey]
      ,[CustomerKey]
      --,[PromotionKey]
      --,[CurrencyKey]
      ,[SalesTerritoryKey]
      ,[SalesOrderNumber]
      --,[SalesOrderLineNumber]
      --,[RevisionNumber]
      ,[OrderQuantity]
      ,[UnitPrice]
      ,[ExtendedAmount]
      --,[UnitPriceDiscountPct]
      --,[DiscountAmount] there are no discounts
      --,[ProductStandardCost] thus this is always equal to TotalProductCost
      ,[TotalProductCost]
      ,[SalesAmount]
	  ,[SalesAmount] - [TotalProductCost] AS Revenue
      --,[TaxAmt]
      ,[Freight]
      --,[CarrierTrackingNumber]
      --,[CustomerPONumber]
      ,[OrderDate]
      ,[DueDate]
      ,[ShipDate]
	  , DATEDIFF(Day, OrderDate, ShipDate) AS DaysUntilArrived
  FROM [AdventureWorksDW2022].[dbo].[FactInternetSales]
